# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(box.lsp)
library(bsicons)
library(bslib)
library(dplyr)
library(ggplot2)
library(gt)
library(nflfastR)
library(nflplotR)
library(nflreadr)
library(nflseedR)
library(reactable)
library(reactablefmtr)
library(rhino)
library(stringr)
library(thematic)
library(treesitter)
library(treesitter.r)
